In [8]:
import numpy as np
import pytest
from sklearn.linear_model import LinearRegression

class LinearRegr:
    def fit(self, X, Y):
        # input:
        #  X = np.array, shape = (n, m)
        #  Y = np.array, shape = (n)
        # Finds theta minimising quadratic loss function L, using an explicit formula.
        # Note: before applying the formula to X one should append to X a column with ones.
        n, m = X.shape
        on=np.ones(n).reshape((n,1))
        X_=np.hstack((on, X))
        
        self.theta = np.linalg.inv(X_.T @ X_) @ X_.T @ Y
        return self
    
    def predict(self, X):
        # input:
        #  X = np.array, shape = (k, m)
        # returns:
        #  Y = wektor(f(X_1), ..., f(X_k))
        k, m = X.shape
        Y = self.theta[0] + np.sum(self.theta[1:] * X, axis=1)
        return Y

def test_RegressionInOneDim():
    X = np.array([1,3,2,5]).reshape((4,1))
    Y = np.array([2,5, 3, 8])
    a = np.array([1,2,10]).reshape((3,1))
    expected = LinearRegression().fit(X, Y).predict(a)
    print(expected)
    actual = LinearRegr().fit(X, Y).predict(a)
    assert list(actual) == pytest.approx(list(expected))
    print (actual)

def test_RegressionInThreeDim():
    X = np.array([1,2,3,5,4,5,4,3,3,3,2,5]).reshape((4,3))
    Y = np.array([2,5, 3, 8])
    a = np.array([1,0,0, 0,1,0, 0,0,1, 2,5,7, -2,0,3]).reshape((5,3))
    expected = LinearRegression().fit(X, Y).predict(a)
    print(expected)
    actual = LinearRegr().fit(X, Y).predict(a)
    assert list(actual) == pytest.approx(list(expected))
    print(actual)

In [9]:
test_RegressionInOneDim()

[ 1.8         3.34285714 15.68571429]
[ 1.8         3.34285714 15.68571429]


In [10]:
test_RegressionInThreeDim()

[ 2.25 -1.75  2.75  2.    3.75]
[ 2.25 -1.75  2.75  2.    3.75]
