In [19]:
import numpy as np
import pytest
from sklearn.linear_model import Ridge

class RidgeRegr:
    def __init__(self, alpha = 0.0):
        self.alpha = alpha

    def fit(self, X, Y):
        # input:
        #  X = np.array, shape = (n, m)
        #  Y = np.array, shape = 👎
        # Finds theta (approximately) minimising quadratic loss function L with Ridge penalty,
        # using an iterative method.

        n, m = X.shape
        self.theta = np.zeros(m+1)
        c = 0.001
        result = False

        while result == False:
            gradient_L = np.zeros(m+1)
            gradient_L[0] = -2 * sum(Y - X @ self.theta[1:] - self.theta[0])
            
            for i in range(m):
                gradient_L[i+1] = 2*sum((Y - X @ self.theta[1:] - self.theta[0])*(-X[:,i])) + 2*self.alpha*self.theta[i+1]
            self.theta = self.theta - c*gradient_L

            if np.linalg.norm(gradient_L) < 10**(-7):
                result = True

        return self
    
    def predict(self, X):
        # input:
        #  X = np.array, shape = (k, m)
        # returns:
        #  Y = wektor(f(X_1), ..., f(X_k))

        k, m = X.shape
        Y = self.theta[0] + np.sum(self.theta[1:] * X, axis=1)
        return Y

def test_RidgeRegressionInOneDim():
    X = np.array([1,3,2,5]).reshape((4,1))
    Y = np.array([2,5, 3, 8])
    X_test = np.array([1,2,10]).reshape((3,1))
    alpha = 0.3
    expected = Ridge(alpha).fit(X, Y).predict(X_test)
    print(expected)
    actual = RidgeRegr(alpha).fit(X, Y).predict(X_test)
    print(actual)
    assert list(actual) == pytest.approx(list(expected), rel=1e-5)

def test_RidgeRegressionInThreeDim():
    X = np.array([1,2,3,5,4,5,4,3,3,3,2,5]).reshape((4,3))
    Y = np.array([2,5, 3, 8])
    X_test = np.array([1,0,0, 0,1,0, 0,0,1, 2,5,7, -2,0,3]).reshape((5,3))
    alpha = 0.4
    expected = Ridge(alpha).fit(X, Y).predict(X_test)
    print(expected)
    actual = RidgeRegr(alpha).fit(X, Y).predict(X_test)
    print(actual)
    assert list(actual) == pytest.approx(list(expected), rel=1e-3)

In [20]:
test_RidgeRegressionInOneDim()

[ 1.88950276  3.38121547 15.31491713]
[ 1.8895028   3.38121549 15.31491702]


In [21]:
test_RidgeRegressionInThreeDim()

[ 0.54685378 -1.76188321  1.58691716  5.15527388  3.66704391]
[ 0.54685342 -1.76188344  1.58691689  5.15527426  3.66704383]
